### ISSUE TITLE
ImportError: No module named '_pywrap_tensorflow_internal' error when running run_nerf.py

### ISSUE THREAD

**Issue by AkshayViru** [bmild/nerf#111]
I am getting the following error after setting up the conda environment and then running run_nerf.py inside it:

Traceback (most recent call last):
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "/home/akshay/anaconda3/envs/nerf/lib-python/3/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_nerf.py", line 5, in <module>
    import tensorflow as tf
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "/home/akshay/anaconda3/envs/nerf/lib-python/3/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/akshay/anaconda3/envs/nerf/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

**Comment by AkshayViru** [comment]
resolved by removing few of the dependencies from environment.yml

**Comment by Raspberrycai1** [comment]
I think @AkshayViru is right. I met the same error when I create the environment from the environment.yml file. But this error is gone when I directly create the environment with specific packages and versions. 
`conda create -n nerf python=3.7 cudatoolkit=10.0 tensorflow-gpu=1.15 -c conda-forge`
