### ISSUE TITLE
Train error `pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0] But your machine only has: [].`

### ISSUE THREAD

**Issue by asbeg** [bmild/nerf#123]
Hello,
I have followed your example to train NERF on my own data. So I have seen you and other guys have some success with single object scene?
 and get this error.

Im using MacOS based M1 Chip, does anyone have any idea what this might be related to. I can't figure out what's going on. Can you explain what the problem might be and how to fix it ? Thank you in advance for any help.

I am trying to run 
```python train.py \
   --dataset_name llff \
   --root_dir /Users/ab/ProjectTest/LLFF \
   --N_importance 64 --img_wh 504 378 \
   --num_epochs 30 --batch_size 1024 \
   --optimizer adam --lr 5e-4 \
   --lr_scheduler steplr --decay_step 10 20 --decay_gamma 0.5 \
   --exp_name exp
```

```Traceback (most recent call last):
  File "train.py", line 178, in <module>
    profiler=hparams.num_gpus==1)
  File "/opt/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 438, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(self.gpus)
  File "/opt/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 712, in parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/opt/anaconda3/envs/nerf_pl/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 678, in sanitize_gpu_ids
    """)
pytorch_lightning.utilities.exceptions.MisconfigurationException: 
                You requested GPUs: [0]
                But your machine only has: [].
```

**Comment by tancik** [comment]
It doesn't look like you are using this repo. Perhaps post this error in https://github.com/kwea123/nerf_pl
