### ISSUE TITLE
I am getting this following issue when I run the command "python run_nerf.py --config config_fern.txt"

### ISSUE THREAD

**Issue by SaadatKhan** [bmild/nerf#175]
Traceback (most recent call last):                                                                                       File "run_nerf.py", line 928, in <module>                                                                                train()                                                                                                              File "run_nerf.py", line 590, in train                                                                                   spherify=args.spherify)                                                                                              File "/home/yu_gmu/nerf/load_llff.py", line 246, in load_llff_data                                                       poses, bds, imgs = _load_data(basedir, factor=factor) # factor=8 downsamples original imgs by 8x                     File "/home/yu_gmu/nerf/load_llff.py", line 70, in _load_data                                                            sh = imageio.imread(img0).shape                                                                                      File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/__init__.py", line 97, in imread              return imread_v2(uri, format=format, **kwargs)                                                                       File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/v2.py", line 226, in imread                   with imopen(uri, "ri", **imopen_args) as file:                                                                       File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/core/imopen.py", line 208, in imopen          plugin_instance = candidate_plugin(request, **kwargs)                                                                File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/config/plugins.py", line 107, in partial_legacy_plugin                                                                                                               return LegacyPlugin(request, legacy_plugin)                                                                          File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/core/legacy_plugin_wrapper.py", line 80, in __init__                                                                                                                 if not self._format.can_read(request):                                                                               File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/core/format.py", line 242, in can_read        return self._can_read(request)                                                                                       File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/plugins/pillow_legacy.py", line 264, in _can_read                                                                                                                    Image = self._init_pillow()                                                                                          File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/plugins/pillow_legacy.py", line 250, in _init_pillow                                                                                                                 from PIL import Image                                                                                                File "/home/yu_gmu/anaconda3/envs/nerf/lib/python3.7/site-packages/PIL/Image.py", line 100, in <module>                  from . import _imaging as core                                                                                     ImportError: libtiff.so.5: cannot open shared object file: No such file or directory   

Could you help?

**Comment by tancik** [comment]
I would try some of the solutions here - https://github.com/rm-hull/luma.led_matrix/issues/154

**Comment by yinghaopeng** [comment]
I am also meet this problem when I debug this nerf project. How can I solve this problem?

**Comment by yinghaopeng** [comment]
AH,I find a method to solve this problem by constructing a soft link between libtiff.so.6 to libtiff.so.5, but I have found a simple method by using "pip install -U Pillow -i https://pypi.tuna.tsinghua.edu.cn/simple" to solve this problem with this nerf project.

**Comment by PoyrazTahan** [comment]
I tried this and it worked for me

python run_nerf.py --config configs/fern.txt

**Comment by yinghaopeng** [comment]
okok, I had tried to change my python venv and found the code can run normal. Thank you for your help.
&nbsp;


penkingco
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Poyraz ***@***.***&gt;; 
发送时间: 2023年3月30日(星期四) 上午6:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bmild/nerf] I am getting this following issue when I run the command &quot;python run_nerf.py --config config_fern.txt&quot; (Issue #175)





 
我试过这个，它对我有用
 
python run_nerf.py --config configs/fern.txt
