### ISSUE TITLE
Error with python run_nerf.py --config config_fern.txt

### ISSUE THREAD

**Issue by guillermogilg99** [bmild/nerf#196]
After following the quickstart guide, I'm getting the following error when running python run_nerf.py --config config_fern.txt:

Traceback (most recent call last):
  File "run_nerf.py", line 928, in <module>
    train()
  File "run_nerf.py", line 590, in train
    spherify=args.spherify)
  File "/home/guillermogg/Escritorio/NORDIC/NeuralNetworks/nerf/load_llff.py", line 246, in load_llff_data
    poses, bds, imgs = _load_data(basedir, factor=factor) # factor=8 downsamples original imgs by 8x
  File "/home/guillermogg/Escritorio/NORDIC/NeuralNetworks/nerf/load_llff.py", line 114, in _load_data
    imgs = imgs = [imread(f)[...,:3]/255. for f in imgfiles]
  File "/home/guillermogg/Escritorio/NORDIC/NeuralNetworks/nerf/load_llff.py", line 114, in <listcomp>
    imgs = imgs = [imread(f)[...,:3]/255. for f in imgfiles]
  File "/home/guillermogg/Escritorio/NORDIC/NeuralNetworks/nerf/load_llff.py", line 110, in imread
    return imageio.imread(f, ignoregamma=True)
  File "/home/guillermogg/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/guillermogg/anaconda3/envs/nerf/lib/python3.7/site-packages/imageio/v2.py", line 360, in imread
    result = file.read(index=0, **kwargs)
TypeError: read() got an unexpected keyword argument 'ignoregamma'

I've tested some of the solutions provided in issue #175 but it's not working and would appreciate some help.

**Comment by guillermogilg99** [comment]
I still didn't find a solution to this

**Comment by HMingXin** [comment]
In load_llff.py line 124, return imageio.imread(f,)

**Comment by seanjkanderson** [comment]
See https://github.com/bmild/nerf/issues/190
