### ISSUE TITLE
issues with generating poses for own dataset

### ISSUE THREAD

**Issue by dilaratank** [bmild/nerf#57]
Hi!

I am a student Artificial Intelligence and I am working on a project using NeRF with a group of other students. We are in possession of a dataset that is made by a company we do the project for. The data consists of images such as the one that is attached (but the whole object is visible, right now it is copressed). 
![Webp net-compress-image](https://user-images.githubusercontent.com/66127366/84271119-004a4700-ab2c-11ea-909a-af59299e8c3a.jpg)

However, we cannot generate poses. The output of the LLFF script is:

```
Features extracted
Features matched
Sparse map created
Finished running COLMAP, see /content/drive/My Drive/nerf/kan_new/colmap_output.txt for logs
Post-colmap
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 274, in gen_poses
    poses, pts3d, perm = load_colmap_data(basedir)
  File "/content/LLFF/llff/poses/pose_utils.py", line 14, in load_colmap_data
    camdata = read_model.read_cameras_binary(camerasfile)
  File "/content/LLFF/llff/poses/colmap_read_model.py", line 115, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/nerf/kan_new/sparse/0/cameras.bin'
```

And sometimes we do not have this error but it only says 'no poses could be extracted'.

Here also the output of colmap: 
[colmap_output(1).txt](https://github.com/bmild/nerf/files/4758604/colmap_output.1.txt)

Is there something wrong with the pictures? How can we fix this?

**Comment by theCodes7** [comment]
For me, rerunning the the steps from scratch helped to solve this. Another attempt you can make is to use COLMAP gui that gives the similar output folders.
