### ISSUE TITLE
Crash when running test example

### ISSUE THREAD

**Issue by krikru** [bmild/nerf#80]
When I run `python run_nerf.py --config config_fern.txt`, I get an error:

```
2020-11-04 01:13:04.722398: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at summary_kernels.cc:57 : Not found: Failed to create a directory: ./logs\summaries\fern_test; No such file or directory
Traceback (most recent call last):
  File "D:/third-part/nerf/run_nerf.py", line 928, in <module>
    train()
  File "D:/third-part/nerf/run_nerf.py", line 754, in train
    os.path.join(basedir, 'summaries', expname))
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\tensorflow_core\python\ops\summary_ops_v2.py", line 438, in create_file_writer
    filename_suffix=filename_suffix))
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\tensorflow_core\python\ops\summary_ops_v2.py", line 213, in __init__
    self._init_op = init_op_fn(self._resource)
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\tensorflow_core\python\ops\gen_summary_ops.py", line 184, in create_summary_file_writer
    name=name, ctx=_ctx)
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\tensorflow_core\python\ops\gen_summary_ops.py", line 224, in create_summary_file_writer_eager_fallback
    name=name)
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: ./logs\summaries\fern_test; No such file or directory [Op:CreateSummaryFileWriter]
```

I use Windows 10 64-bit.

**Comment by Brendamus** [comment]
I'm also having this issue.

**Comment by tancik** [comment]
Try creating a `./logs\summaries` folder.

**Comment by Brendamus** [comment]
`(nerf) C:\Workspace\Nerf\nerf>bash download_example_data.sh
--2020-11-05 00:46:32--  https://people.eecs.berkeley.edu/~bmild/nerf/tiny_nerf_data.npz%0D
Resolving people.eecs.berkeley.edu (people.eecs.berkeley.edu)... 128.32.189.73
Connecting to people.eecs.berkeley.edu (people.eecs.berkeley.edu)|128.32.189.73|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-05 00:46:32 ERROR 404: Not Found.

--2020-11-05 00:46:32--  https://people.eecs.berkeley.edu/~bmild/nerf/nerf_example_data.zip%0D
Resolving people.eecs.berkeley.edu (people.eecs.berkeley.edu)... 128.32.189.73
Connecting to people.eecs.berkeley.edu (people.eecs.berkeley.edu)|128.32.189.73|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-05 00:46:33 ERROR 404: Not Found.

download_example_data.sh: line 5: unzip: command not found
download_example_data.sh: line 6: cd: $'..\r': No such file or directory
`

**Comment by tancik** [comment]
Oh, it looks like you are just trying to download the data. The script was made for linux so windows may be causing you issues.

If you look at the `download_example_data.sh` script you will see that it is just downloading and unziping some files. It's probably easier to just do it manually.

**Comment by Brendamus** [comment]
Oh. I didn't realize. I'll just do it manually then. Thanks for your help!
