### ISSUE TITLE
tboard_val_imgs folder missing when running test example

### ISSUE THREAD

**Issue by krikru** [bmild/nerf#83]
When having fixed [two](https://github.com/bmild/nerf/issues/80) [previous](https://github.com/bmild/nerf/issues/81) issues, I get a new crash (still when running `python run_nerf.py --config config_fern.txt`):

```
Traceback (most recent call last):
  File "D:/third-part/nerf/run_nerf.py", line 928, in <module>
    train()
  File "D:/third-part/nerf/run_nerf.py", line 901, in train
    imageio.imwrite(os.path.join(testimgdir, '{:06d}.png'.format(i)), to8b(rgb))
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\imageio\core\functions.py", line 303, in imwrite
    writer = get_writer(uri, format, "i", **kwargs)
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\imageio\core\functions.py", line 217, in get_writer
    request = Request(uri, "w" + mode, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\imageio\core\request.py", line 124, in __init__
    self._parse_uri(uri)
  File "D:\ProgramData\Miniconda3\envs\nerf\lib\site-packages\imageio\core\request.py", line 265, in _parse_uri
    raise FileNotFoundError("The directory %r does not exist" % dn)
FileNotFoundError: The directory 'D:\\third-part\\nerf\\logs\\fern_test\\tboard_val_imgs' does not exist
```

An easy workaround is to manually create the `tboard_val_imgs` folder in `logs\fern_test` (I'm running Windows 10; hence the backslash in the path).

**Comment by Then0109** [comment]
Sorry to bother you. I think the reason might be that you rerun the model after deleting the tboard_val_imgs folder and you didn't delete the fern_test folder and summaries folder at the same time?
